### ISSUE TITLE
Cannot connect to kubectl proxy

### ISSUE THREAD

**Issue by koss822** [scholzj/aws-minikube#14]
Hello,

I did a clear installation, and I had few issues

1) documentation - there is written that it is enough just to run "kubectl proxy", this is not really true, you have to export different port than 8080 first:

`export KUBERNETES_MASTER=https://your.domain:6443`

2) documentation - it is not mentioned that if you are using SSL which is enabled by default, you have to use also CA validation, so 

`kubectl --certificate-authority=/etc/kubernetes/pki/ca.crt`

3) RBAC - In documantation is stated 

> This is intentional for security reasons (no authentication / authorization) 

This is not exactly true with new version of Kubernetes, which is included in actual package. You have to use RBAC authentification according to Kubernetes documentation. I am still fighting how to get rid of this message

>   "message": "services \"https:kubernetes-dashboard:\" is forbidden: User \"system:anonymous\" cannot get services/proxy in the namespace \"kube-system\"",

After running
`kubectl --certificate-authority=/etc/kubernetes/pki/ca.crt proxy`

and tunneling it through SSH to my localhost

and accessing

`http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/login`

Can you please help. I cannot even get pods even when I use

`kubeadm token list`

and use selected tokens because tokens has low privileges

> [root@ip-10-0-0-18 kubernetes]# kubeadm token list
> TOKEN                     TTL       EXPIRES                USAGES                   DESCRIPTION   EXTRA GROUPS
> ******* 23h       2018-09-30T14:34:31Z   authentication,signing   <none>        system:bootstrappers:kubeadm:default-node-token
> 
> ********   <forever>   <never>   authentication,signing   <none>    system:bootstrappers:kubeadm:default-node-token
> 

I need a token with system.master privileges but I have no idea how to get it.

**Comment by scholzj** [comment]
This is what I normally do and what works:

1. SCP the `kubeconfig` from the minukube (the remote host) to your localhost. The `scp` command is printed at the end of the Terraform execution.
2. Do `export KUBECONFIG=<pathToWhereYouCopiedTheKubeconfigFile>`
3. Do `kubectl proxy` on your local computer, not in the AWS machine

For this I never needed to do anything with certificates etc. These should be all in the `kubeconfig` file.

**Comment by koss822** [comment]
Hello,

firstly I am very happy with your prompt and fast response. When I copied kubeconfig to my local machine I was able to see login screen to dashboard on 

- http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/login

Unfortunately I was not able to login with kubeconfig. I had to create an user following documentation here
- https://github.com/kubernetes/dashboard/wiki/Creating-sample-user

After this I was able to login to Dashboard with Token :1st_place_medal: 

It would be perfect if you would be update documentation also for others because it is very difficult for a person who is beginning with Kubernetes to start when a lot of things is not working out of the box even in demo installation.

**Comment by scholzj** [comment]
TBH, the login screen in the dashboard should normally not appear.  If it does, I think there is some button to either continue or skip it (I do not have it installed right now to check it). Since the _AWS Minikube_ is more or less intended for development work, the Dashboard is deployed with the rights it needs and should not require login. I will have a look why the login screen appears sometimes. Thanks.
