### ISSUE TITLE
Confused, is this Minikube or just a single node Kubernetes?

### ISSUE THREAD

**Issue by ricklamers** [scholzj/aws-minikube#15]
As per the title, I'm a bit confused.

Is this Terraform configuration installing a regular Kubernetes installation configured to have a single node? Or is it actually installing the 'real' minikube (https://github.com/kubernetes/minikube/releases/tag/v1.5.2)?

I'm a bit of a noob when it comes to the difference between the two so please tell me if I'm misunderstanding.

- Kind regards

**Comment by scholzj** [comment]
It is not using the actual Minikube binaries or anything. It gives you a single node cluster deployment similar to (inspired by) Minikube, but in AWS and with full AWS integration (so you can use real loadbalancers, real EBS volumes etc.).

**Comment by ricklamers** [comment]
Thanks for responding. No longer confused, I guess the explicit title of Minikube made me conclude that it was using their binaries. Perhaps a short mention in the README.

Awesome repo regardless!
