### ISSUE TITLE
Initializing modules... - minikube in  Error: Unreadable module directory

### ISSUE THREAD

**Issue by keremceliker** [scholzj/aws-minikube#16]
Hello,

When i run the terraform init in aws-minikube folder as you provided guided steps, im getting following error. Am i missing minor something  ? How can i fix this issue ?

_Test2 Folder has all the files by the way.

C:\Users\andromeda\26042020_Test2>terraform init

Initializing modules...
- minikube in

Error: Unreadable module directory

Unable to evaluate directory symlink: CreateFile ..\terraform-aws-minikube:
The system cannot find the file specified.

Error: Failed to read module directory

Module directory  does not exist or cannot be read.

Error: Unreadable module directory

Unable to evaluate directory symlink: CreateFile ..\terraform-aws-minikube:
The system cannot find the file specified.

Error: Failed to read module directory

Module directory  does not exist or cannot be read.

**Comment by scholzj** [comment]
Sorry, it looks like in one of the commits I added some changes which were supposed to be local only for testing :-(. I'm just working on Kube 1.18.2 - I will get it fixed.

**Comment by keremceliker** [comment]
Can i try to run now to build ? :)

**Comment by scholzj** [comment]
I think that all you need is to change this in the main.tf:

```
  source = "../terraform-aws-minikube/"
```

for this:

```
  source = "scholzj/minikube/aws"
```

**Comment by keremceliker** [comment]
Thanks ! It really works. But we have a issue as the follows now. 

 Error: no matching Route53Zone found

  on .terraform\modules\minikube\terraform-aws-minikube-1.11.1\main.tf line 239, in data "aws_route53_zone" "dns_zone":
 239: data "aws_route53_zone" "dns_zone" {

**Comment by scholzj** [comment]
You need to specify a DNS Zone configuried in AWS Route53. If you don't have any domains in Route53, you should be able to create a private DNS zone. You will nto be able to really use the DNS names - only IPs, but it should work IIRC.

**Comment by scholzj** [comment]
(it is configured using the `hosted_zone` and `hosted_zone_private` options)

**Comment by keremceliker** [comment]
If its possible, can you share a sample output to create and run them on the terraform side according to create a new private DNS Zone. You're a really good teacher, and I'm learning with your support.

**Comment by scholzj** [comment]
Sorry, I do not really havy any terraform scripts for that. I normally use just a zone which I created manually long time ago using the AWS console. The settings looks like this (from `example.tfvars`):

```
hosted_zone = "my-domain.com"
hosted_zone_private = false
```

IIRC the seting up in the AWS console is normally straight forward - you just follow the wizard.

**Comment by scholzj** [comment]
I pubhlished new release where the terrform module should fixed now.

**Comment by keremceliker** [comment]
Oh thanks ! I going to try it now and get back to you quickly :)

**Comment by keremceliker** [comment]
It works now after you published new release. Thanks for the quick response !
