### ISSUE TITLE
Specify custom AMI?

### ISSUE THREAD

**Issue by StevenACoffman** [scholzj/aws-minikube#7]
Where I work, we use Netflix BLESS, and we would like to specify a custom AMI running on the EC2 instance, so we can configured the EC2 instance to trust our self-signed CA.

BLESS uses SSH certificates, added to OpenSSH in 5.4. SSH certificates allow a certificate authority to sign a user’s public key, along with a list of constraints; the user presents this certificate to the server during authentication. The server only needs to trust the CA, and does not need previous knowledge of the user’s public key.

Do you have an interest in an optional parameter for specifying a custom AMI?

**Comment by scholzj** [comment]
Technically, this would need to be implemented in [terraform-aws-minikube](https://github.com/scholzj/terraform-aws-minikube) first. That is the Terraform module which does the work. This repo pretty much just wraps around it.

But in general I do not have problem with such parameter if it is optional. I'm not exactly sure about the best way to implement it. Terraform isn't the best think around when trying to create some "if ... else ..." construct. And the Terraform configuration doesn't have a hardcoded AMI image ID. Instead it is searching for the AMI:

```hcl
data "aws_ami" "centos7" {
  most_recent = true
  owners      = ["aws-marketplace"]

  filter {
    name   = "product-code"
    values = ["aw0evgkw8e5c1q413zgy5pjce"]
  }

  filter {
    name   = "architecture"
    values = ["x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}
```

So maybe the best way would be to try to allow to configure the options. Or do you have some other idea how to implement it?

**Comment by StevenACoffman** [comment]
I'm honestly not very familiar with Terraform, but I think you can have defaults, right? So if we could configure the filter options from those defaults to something else, like a different owner and an AMI id instead of a product_code?

**Comment by scholzj** [comment]
So, this should be now implemented. You have to update the module (`terraform init --upgrade=true`) and set the variable `ami_image_id`. Please give it a try and let me know.
